# Use an official Python runtime as a base image
FROM python:3.10.13-bookworm

# Install MLflow
RUN pip install mlflow

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
